clientes/urls.py
# clientes/urls.py
from django.urls import path
from .views import lista_clientes, adicionar_cliente, detalhes_cliente, editar_cliente, excluir_cliente

app_name = 'clientes'

urlpatterns = [
    path('lista_clientes/', lista_clientes, name='lista_clientes'),
    path('adicionar/', adicionar_cliente, name='adicionar_cliente'),
    path('<int:cliente_id>/', detalhes_cliente, name='detalhes_cliente'),
    path('<int:cliente_id>/editar/', editar_cliente, name='editar_cliente'),
    path('<int:cliente_id>/excluir/', excluir_cliente, name='excluir_cliente'),
]

crud/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),  # Include your clientes.urls here    path('',include('produtos.urls')),
    path('clientes/', include('clientes.urls', namespace='clientes')),  # Include your clientes.urls here    path('',include('produtos.urls')),
    path('produtos/', include('produtos.urls', namespace='produtos')),
    path('grupoprodutos', include('grupoprodutos.urls', namespace='grupoprodutos')),
    path('vendas/', include('vendas.urls', namespace='vendas')),

    path('vendedor/', include('vendedor.urls', namespace='vendedor')),
    path('itemvenda/', include('itemvenda.urls', namespace='itemvenda')),
    
    
    
]

home/urls.py
from django.urls import path
from .views import home

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    # Adicione outras URLs conforme necessário
]

produtos/urls.py
from django.urls import path
from .views import lista_produtos, adicionar_produto, detalhes_produto, editar_produto, excluir_produto

app_name = 'produtos'

urlpatterns = [
    path('', lista_produtos, name='lista_produtos'),
    path('produtos/adicionar/', adicionar_produto, name='adicionar_produto'),
    path('produtos/<int:produto_id>/', detalhes_produto, name='detalhes_produto'),
    path('produtos/<int:produto_id>/editar/', editar_produto, name='editar_produto'),
    path('produtos/<int:produto_id>/excluir/', excluir_produto, name='excluir_produto'),
]

vendas/urls.py
from django.urls import path
from .views import lista_vendas, adicionar_venda, detalhes_venda, editar_venda, excluir_venda

app_name = 'vendas'

urlpatterns = [
    path('vendas/', lista_vendas, name='lista_vendas'),
    path('vendas/adicionar/', adicionar_venda, name='adicionar_venda'),
    path('vendas/<int:venda_id>/', detalhes_venda, name='detalhes_venda'),
    path('vendas/<int:venda_id>/editar/', editar_venda, name='editar_venda'),
    path('vendas/<int:venda_id>/excluir/', excluir_venda, name='excluir_venda'),
]

vendedor/urls.py
from django.urls import path
from .views import lista_vendedores, adicionar_vendedor, detalhes_vendedor, editar_vendedor, excluir_vendedor

app_name = 'vendedor'

urlpatterns = [
    path('', lista_vendedores, name='lista_vendedores'),
    path('vendedores/adicionar/', adicionar_vendedor, name='adicionar_vendedor'),
    path('vendedores/<int:vendedor_id>/', detalhes_vendedor, name='detalhes_vendedor'),
    path('vendedores/<int:vendedor_id>/editar/', editar_vendedor, name='editar_vendedor'),
    path('vendedores/<int:vendedor_id>/excluir/', excluir_vendedor, name='excluir_vendedor'),
]

home/views.py
# No arquivo views.py do aplicativo home

from django.shortcuts import render

def home(request):
    return render(request, 'home/home.html')

home/templates/home/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Home</title>
</head>
<body>
    <h1>Bem-vindo à Página Inicial</h1>

    <h2>Clientes</h2>
    <ul>
        <li><a href="{% url 'clientes:lista_clientes' %}">Lista de Clientes</a></li>
        <li><a href="{% url 'clientes:adicionar_cliente' %}">Adicionar Cliente</a></li>
    </ul>

    <h2>Produtos</h2>
    <ul>
        <li><a href="{% url 'produtos:lista_produtos' %}">Lista de Produtos</a></li>
        <li><a href="{% url 'produtos:adicionar_produto' %}">Adicionar Produto</a></li>
    </ul>

    <h2>Vendas</h2>
    <ul>
        <li><a href="{% url 'vendas:lista_vendas' %}">Lista de Vendas</a></li>
        <li><a href="{% url 'vendas:adicionar_venda' %}">Adicionar Venda</a></li>
    </ul>

    <h2>Vendedores</h2>
    <ul>
        <li><a href="{% url 'vendedor:lista_vendedores' %}">Lista de Vendedores</a></li>
        <li><a href="{% url 'vendedor:adicionar_vendedor' %}">Adicionar Vendedor</a></li>
    </ul>

    <h2>Grupos de Produtos</h2>
    <ul>
        <li><a href="{% url 'grupoprodutos:lista_grupoprodutos' %}">Lista de Grupos de Produtos</a></li>
        <li><a href="{% url 'grupoprodutos:adicionar_grupoproduto' %}">Adicionar Grupo de Produto</a></li>
    </ul>

    <h2>Itens de Venda</h2>
    <ul>
        <li><a href="{% url 'itemvenda:lista_itemvenda' %}">Lista de Itens de Venda</a></li>
        <li><a href="{% url 'itemvenda:adicionar_itemvenda' %}">Adicionar Item de Venda</a></li>
        <li><a href="{% url 'home:home' %}">home</a></li>

    </ul>
</body>
</html>